name: package-tauri
description: Package Tauri app
inputs:
  target:
    description: Target platform
    required: true
  release-id:
    description: Release ID
    required: true
  github-token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - name: build-app
      shell: bash
      run: npm run tauri -- build --target ${{ inputs.target }}
